name: Send submodule updates to parent repo

on:
  push:
    branches:
      - develop

jobs:
  update-swui-fsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout switch-ui-fsd repository
        uses: actions/checkout@v2
        with:
          repository: InComm-OLS/switch-ui-fsd
          token: ${{ secrets.SUBMODULE_UPDATE }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Pull Request - switch-ui-fsd
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git checkout -b update-submodules-fsd
          git add --all
          git commit -m "Update submodules"
          git push --set-upstream origin update-submodules-fsd
          gh pr create --base develop --head update-submodules-fsd --title "Update submodules" --body "Updating submodules from switch-ui-fsd"

  update-swui-cvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout switch-ui-cvs repository
        uses: actions/checkout@v2
        with:
          repository: InComm-OLS/switch-ui-cvs
          token: ${{ secrets.SUBMODULE_UPDATE }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Pull Request - switch-ui-cvs
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git checkout -b update-submodules-cvs
          git add --all
          git commit -m "Update submodules"
          git push --set-upstream origin update-submodules-cvs
          gh pr create --base develop --head update-submodules-cvs --title "Update submodules" --body "Updating submodules from switch-ui-cvs"

  update-swui-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout switch-ui-iso repository
        uses: actions/checkout@v2
        with:
          repository: InComm-OLS/switch-ui-iso
          token: ${{ secrets.SUBMODULE_UPDATE }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Pull Request - switch-ui-iso
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git checkout -b update-submodules-iso
          git add --all
          git commit -m "Update submodules"
          git push --set-upstream origin update-submodules-iso
          gh pr create --base develop --head update-submodules-iso --title "Update submodules" --body "Updating submodules from switch-ui-iso"
