name: Send submodule updates to parent repo

on:
  push:
    branches:
      - main

jobs:
  update-swui-fsd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout test2 repository
        uses: actions/checkout@v2
        with:
          repository: Resef001/test2
          token: ${{ secrets.SUBMODULE_UPDATE }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Pull Request - test2
        id: create_pr
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git checkout -b update-submodules-test2
          git add --all
          git commit -m "Update submodules"
          git push --set-upstream origin update-submodules-test2
          gh pr create --base main --head update-submodules-test2 --title "Update submodules" --body "Updating submodules from test"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}     