name: Update Submodules and Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Submodule Branch and Commit Changes
        run: |
          git checkout -b update-submodule-changes
          git add .
          git commit -m "Update submodules"
          git push origin update-submodule-changes

      - name: Create Submodule Pull Request
        id: create_submodule_pr
        run: |
          gh pr create --repo Resef001/test2 --base main --head update-submodule-changes --title "Update submodules" --body "Updating submodules from test"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-submodule-pr:
    needs: update-submodules
    runs-on: ubuntu-latest
    steps:
      - name: Merge Submodule Pull Request
        run: |
          gh pr merge --auto --merge --squash <submodule-pr-number>
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Super Repository Branch
        run: |
          git checkout main
          git pull origin main
          git submodule update --recursive --remote
          git add .
          git commit -m "Update submodule pointer"
          git push origin main

      - name: Create Super Repository Pull Request
        id: create_super_pr
        run: |
          gh pr create --base main --head update-submodule-changes --title "Update submodule pointer" --body "Updating submodule pointer from submodules"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
