name: Update Submodule and Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Create Submodule Branch and Commit Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git checkout -b update-submodule-changes
          git add .
          git commit -m "Update submodules"
          git push origin update-submodule-changes

      - name: Create Submodule Pull Request
        run: |
          gh pr create --repo Resef001/test2 --base main --head update-submodule-changes --title "Update submodules" --body "Updating submodules from test"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
