name: Send submodule pull request to parent repo

on:
  push:
    branches:
      - main

jobs:
  update-swui-fsd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v2
        with:
          repository: Resef001/test2
          token: ${{ secrets.SUBMODULE_UPDATE }}
          submodules: true

      - name: Create feature branch
        run: |
          git checkout -b feature/update-submodule

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit submodule changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"

      - name: Push feature branch
        run: |
          git push --force origin feature/update-submodule

      - name: Check if pull request already exists
        id: check_pr
        run: |
          PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/Resef001/test2/pulls?state=open" | jq '.[] | select(.head.ref == "feature/update-submodule") | .number')
          echo "::set-output name=pr_exists::$(if [[ -n $PR_COUNT ]]; then echo true; else echo false; fi)"
        shell: bash

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y

      - name: Create Pull Request if it doesn't exist
        if: steps.check_pr.outputs.pr_exists == 'false'
        run: |
          hub pull-request -m "Update submodules" -b main -h feature/update-submodule